services:
  - name: accounntsgoal-frontend
    type: web
    env: node
    buildCommand: npm run build
    startCommand: npm run dev
    routes:
      - type: rewrite
        source: /
        destination: /index.html
      - type: rewrite
        source: /.*
        destination: /index.html
